const appname = "Capyshop";
const appversion = "Version 1.0.0";

const email = "Email";
const emailHint = "a@gmail.com";
const password = "Mật khẩu";
const passwordHint = "********";
const forgetPass = "Quên mật khẩu";
const login = "Đăng nhập";
const signup = "Đăng kí";
const createNewAccount = "Hoặc tạo tài khoản mới";
const loginWith = "Đăng nhập với";
const retypePW = "Nhập lại mật khẩu";
const retypePWHint = "Vui lòng nhập lại mật khẩu";
const name = "Tên của bạn";
const nameHint = "Vui lòng nhập tên của bạn";
const RiengTu = "Privacy";
const termAndCond = "Term and condition";
const DaCoTK = "Nếu đã có tài khoản? ";

const home = "Trang chủ",
    categories = "Thương hiệu",
    cart = "Giỏ hàng",
    account = "Tài khoản";
const searchanything = "Tìm kiếm...",
    todayDeal = "Deal hời hôm nay",
    flashsale = "Siêu sale",
    topSellers = "Top Sản phẩm",
    brand = "Thương hiệu",
    featuredCategories = "Danh mục nổi bật",
    topCategories = "Top danh mục",
    womenDress = "Woman Dress",
    girlsWatches = "Girl Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boy Glasses",
    tShirts = "T-Shirts",
    featureProduct = "Feature Products",
    girlsDress = "Girl Dress";
//category
const Iphone = "Iphone",
    Samsung = "Samsung",
    Nokia = "Nokia",
    XiaoMi = "XiaoMi";
//item detail
const video = "video",
    reviews = "reviews",
    sellerPolicy = "Seller policy",
    returnPolicy = "Return Policy",
    supportPolicy = "Support policy",
    productUMayLike = "Sản phẩm bạn có thể sẽ thích";
