// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUk03b9kKPHo6DR0UP6TLzkbjnXkSnnWk',
    appId: '1:1033863568078:web:85a679eb0a349b12108e9f',
    messagingSenderId: '1033863568078',
    projectId: 'damh-flutter',
    authDomain: 'damh-flutter.firebaseapp.com',
    storageBucket: 'damh-flutter.firebasestorage.app',
    measurementId: 'G-882HM98ZVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPAS31ujkyywH8B4wd-9hMsI3RXXulgI',
    appId: '1:1033863568078:android:767dfdf24c50498e108e9f',
    messagingSenderId: '1033863568078',
    projectId: 'damh-flutter',
    storageBucket: 'damh-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAr5YF-OXPfb8xw8dowO3RHNe5X0cOT0',
    appId: '1:1033863568078:ios:0fb39c4d2e3f9495108e9f',
    messagingSenderId: '1033863568078',
    projectId: 'damh-flutter',
    storageBucket: 'damh-flutter.firebasestorage.app',
    iosBundleId: 'com.example.damhFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAr5YF-OXPfb8xw8dowO3RHNe5X0cOT0',
    appId: '1:1033863568078:ios:0fb39c4d2e3f9495108e9f',
    messagingSenderId: '1033863568078',
    projectId: 'damh-flutter',
    storageBucket: 'damh-flutter.firebasestorage.app',
    iosBundleId: 'com.example.damhFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUk03b9kKPHo6DR0UP6TLzkbjnXkSnnWk',
    appId: '1:1033863568078:web:44f32e6ed4239c47108e9f',
    messagingSenderId: '1033863568078',
    projectId: 'damh-flutter',
    authDomain: 'damh-flutter.firebaseapp.com',
    storageBucket: 'damh-flutter.firebasestorage.app',
    measurementId: 'G-N03R7VDX84',
  );
}
